spring.application.name=WatchTime

spring.profiles.active=${APP_PROFILE:develop}

spring.servlet.multipart.max-request-size=1000MB
spring.servlet.multipart.max-file-size=1000MB

jwt.secret.key=958fabff1c020a4edea8a9a01e929e2baca29f59951998d7de5600a8a0fb9774
jwt.expiration.time=60000
